# Travis-CI configuration file for SuperTuxKart Editor
#
# Configuration manual:
# http://docs.travis-ci.com/user/customizing-the-build/
# http://docs.travis-ci.com/user/languages/cpp/

language: cpp

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true

env:
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libxxf86vm-dev libphysfs1 libphysfs-dev zlib1g zlib1g-dev
  -

before_script:
  - export THREADS=`nproc`
  - echo "THREADS = $THREADS"
  - cmake --version

script:
  # Clean from previous Travis build
  - git clean -f
  # Then build:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make VERBOSE=1 -j $THREADS
