# Travis-CI configuration file for SuperTuxKart Editor
#
# Configuration manual:
# http://docs.travis-ci.com/user/customizing-the-build/
# http://docs.travis-ci.com/user/languages/cpp/

language: cpp
sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

matrix:
  fast_finish: true

env:
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

before_script:
  - export THREADS=$((`nproc` + 1))
  - echo "THREADS = $THREADS"
  - free -mt

script:
  - mkdir "build"
  - cd "build"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make VERBOSE=1 -j $THREADS

addons:
  apt:
    packages:
      - build-essential
      - libxxf86vm-dev
      - libphysfs1
      - libphysfs-dev
      - zlib1g
      - zlib1g-dev

notifications:
  irc:
    channels:
      - "irc.freenode.org#supertuxkart"
    skip_join: false
    use_notice: true
    template:
      - "[%{repository}#%{branch} @%{commit}] %{author}): %{message}"
      - "Diff: %{compare_url}"
      - "Build: %{build_url}"
